"""Ingest OpenHands trajectories (nebius/SWE-rebench-openhands-trajectories),
generated by Qwen3-Coder-480B-A35B-Instruct (2025) on SWE-rebench tasks. A
different scaffold (OpenHands v0.54) from SWE-agent, so we parse its structured
tool-calls into the common schema. Gold patches join from nebius/SWE-rebench.
Free replay, no execution sandbox required.
"""
from __future__ import annotations
import itertools, json, re
from .schema import Trajectory, Step, Action

DS = "nebius/SWE-rebench-openhands-trajectories"
GOLD_DS = "nebius/SWE-rebench"
MODEL = "Qwen3-Coder-480B"

_GOLD = None
_WS = re.compile(r"^/workspace/[^/]+/")


def load_gold() -> dict[str, str]:
    global _GOLD
    if _GOLD is None:
        from datasets import load_dataset
        g = {}
        for split in ("test", "train"):
            try:
                ds = load_dataset(GOLD_DS, split=split)
            except Exception:
                continue
            for r in ds:
                p = r.get("patch") or r.get("gold_patch") or ""
                if r.get("instance_id") and p:
                    g[r["instance_id"]] = p
        _GOLD = g
    return _GOLD


def _strip(path: str) -> str:
    return _WS.sub("", path or "").lstrip("/")


def _action_from_toolcall(tc: dict) -> Action | None:
    fn = (tc.get("function") or {})
    name = fn.get("name") or ""
    try:
        args = json.loads(fn.get("arguments") or "{}")
    except Exception:
        args = {}
    if name == "str_replace_editor" or name == "str_replace_based_edit_tool":
        cmd = args.get("command") or ""
        path = _strip(args.get("path") or "")
        if cmd == "create":
            return Action(raw=json.dumps(args)[:400], cmd="create", args=path,
                          edit_content=args.get("file_text") or "", target_file=path)
        if cmd in ("str_replace", "insert"):
            return Action(raw=json.dumps(args)[:400], cmd="edit", args=path,
                          edit_content=args.get("new_str") or "", target_file=path)
        return Action(raw="view", cmd="open", args=path, target_file=path)
    if name in ("execute_bash", "run_ipython", "bash"):
        return Action(raw=(args.get("command") or "")[:200], cmd="bash",
                      args=(args.get("command") or "")[:200])
    # think / finish / other: reasoning-only, not a file action
    return None


def _normalize(row: dict) -> Trajectory:
    msgs = row.get("trajectory") or []
    steps, ai_i = [], 0
    for i, m in enumerate(msgs):
        if m.get("role") != "assistant":
            continue
        tcs = m.get("tool_calls") or []
        action = None
        for tc in tcs:
            a = _action_from_toolcall(tc)
            if a is not None:
                action = a
                break
        # observation = next tool message content
        obs = ""
        for j in range(i + 1, len(msgs)):
            if msgs[j].get("role") == "tool":
                obs = str(msgs[j].get("content") or "")
                break
            if msgs[j].get("role") == "assistant":
                break
        text = str(m.get("content") or "")
        if not text and tcs:  # think tool carries reasoning in arguments
            try:
                text = json.loads(tcs[0].get("function", {}).get("arguments") or "{}").get("thought", "")
            except Exception:
                text = ""
        steps.append(Step(index=ai_i, raw_index=i, role="ai", text=text,
                          action=action, observation=obs[:4000]))
        ai_i += 1
    return Trajectory(instance_id=row.get("instance_id", ""), model_name=MODEL,
                      resolved=bool(row.get("resolved")), steps=steps,
                      generated_patch=row.get("model_patch", "") or "",
                      exit_status=row.get("exit_status", "") or "", source="swe-rebench-openhands")


def ingest(max_failed=150, max_resolved=80, scan_cap=4000) -> list[Trajectory]:
    from datasets import load_dataset
    gold = load_gold()
    ds = load_dataset(DS, split="train", streaming=True)
    failed, resolved = [], []
    for row in itertools.islice(ds, scan_cap):
        if row.get("instance_id") not in gold:
            continue
        t = _normalize(row)
        if t.n_steps < 3:
            continue
        t.gold_patch = gold[t.instance_id]
        if not t.resolved and len(failed) < max_failed:
            failed.append(t)
        elif t.resolved and len(resolved) < max_resolved:
            resolved.append(t)
        if len(failed) >= max_failed and len(resolved) >= max_resolved:
            break
    print(f"[openhands/{MODEL}] {len(failed)} failed / {len(resolved)} resolved "
          f"(gold pool {len(gold)})")
    return failed + resolved
